### ISSUE TITLE
Why are resources required on the hook call and route definition?

### ISSUE THREAD

**Issue by dan-dr** [atlassian-labs/react-resource-router#20]
Interesting library. I saw that the created resources are used twice, once when you define the routes and once when you `useResource`.

```javascript
// routes.js
export const appRoutes = [
  {
    name: 'home',
    path: '/',
    exact: true,
    component: Home,
    resources: [homeResource],
  },
];

// components.jsx
import homeResource from '../resources';

const resource = useResource(homeResource)
```

Why is that?
Shouldn't I be able to do
```javascript
// resources: [homeResource]
const homeResource = useResource()
// resources: [homeResource, aboutResource]
const [homeResource, aboutResource] = useResource()
```

**Comment by rohan-deshpande** [comment]
Hi, @dan-dr thanks for your interest!

The resources are assigned to the route so that there is a clear, statically analysable source of truth for all of the route's needs. It is much easier to see not only the UI which is relevant to the route (`component`) but also the data that is required to render the most meaningful parts of that UI. These resources on the route are also used to render the application on the server. 

In terms of usage in components, `useResource` requires that you provide it the resource that you want to use to access that resource's current state. You can check out the docs for more info on how that works https://atlassian-labs.github.io/react-resource-router/#/resources/usage

It's possible that if you are using something like Apollo or Relay that you may not need `useResource` at all.
